fail_fast: true

repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
#          - --remove-all-unused-imports

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--diff, --check, -l 79]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
          - --line-length=79
          - --src=graph_cast
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
#        args:
#          - --module lm_service
        exclude: (^test/|^run/)
#        args: [--strict]

#  - repo: https://github.com/pre-commit/mirrors-pylint
#    rev: v2.14.5
#    hooks:
#      - id: pylint
#        args: [--disable=all, --enable=unused-import]
