site_name: GraphCast
site_url: https://growgraph.github.io/graphcast
repo_url: https://github.com/growgraph/graphcast
repo_name: growgraph/graphcast
copyright: Copyright &copy; 2025 GrowGraph

theme:
    name: material
    user_color_mode_toggle: true
    palette:
    -   scheme: default
        primary: green
        accent: deep purple
        toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
    -   scheme: slate
        primary: deep purple
        accent: yellow
        toggle:
            icon: material/toggle-switch
            name: Switch to light mode
    logo: assets/project_logo.png
    icon:
        repo: fontawesome/brands/github
    favicon: assets/favicon.ico

plugins:
-   search
-   glightbox
-   gen-files:
        scripts:
        -   docs/gen_pages.py
-   literate-nav
-   mkdocstrings:
        default_handler: python
        handlers:
            python:
                options:
                    extra:
                        show_source: true
                        show_root_toc_entry: false
                        docstring_style: google
                        show_submodules: true
                        show_category_heading: true
                        show_if_no_docstring: true
                        setup_commands:
                        -   "import sys"
                        -   "sys.path.append('.')"

nav:
-   Home: index.md
-   Getting Started:
    -   Installation: getting_started/installation.md
    -   Quick Start: getting_started/quickstart.md
-   Concepts: concepts/index.md
-   Examples:
    -   1 - Ingest csv files: examples/example-1.md
    -   2 - Ingest jsons with self-references: examples/example-2.md
-   API Reference: reference/
-   Contributing: contributing.md

markdown_extensions:
-   pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
-   pymdownx.inlinehilite
-   pymdownx.snippets
-   pymdownx.superfences
-   attr_list
-   md_in_html
-   admonition
-   codehilite
-   footnotes
-   meta
-   pymdownx.blocks.caption
-   admonition
-   pymdownx.superfences
-   pymdownx.details
-   pymdownx.tabbed
-   pymdownx.highlight
-   pymdownx.emoji
-   pymdownx.tasklist
-   pymdownx.keys
-   pymdownx.snippets
-   pymdownx.magiclink
-   pymdownx.betterem
-   pymdownx.caret
-   pymdownx.tilde
-   pymdownx.mark
-   pymdownx.smartsymbols
-   pymdownx.arithmatex
-   pymdownx.progressbar
-   pymdownx.escapeall


-   toc:
        permalink: true


