[tool.poetry]
name = "graph_cast"
version = "0.1.0"
description = "tools to cast csv and json files into graph form amenable to ingest into graph databases eg ArangoDB"
authors = ["Alexander Belikov <abelikov@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
python-arango = "~5.2.1"
pyyaml = "^5.3.1"
networkx = "^2.5"
pandas = "^1.1.3"
pygraphviz = "^1.6"
black = "^21.5b2"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
