[tool.poetry]
name = "graph_cast"
version = "0.2"
description = "ETL to cast tabluar and json data types into graphs(collections of vertices and edges)"
authors = ["Alexander Belikov <alexander@growgraph.dev>"]

[tool.poetry.dependencies]
python = "^3.9"
pyyaml = "^5.3.1"
networkx = "^2.5"
pandas = "^1.1.3"
pygraphviz = "^1.6"
black = "^21.5b2"
xmltodict = "^0.12.0"
vulture = "^2.3"
mypy = "^0.942"
python-arango = "^7.3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
