[tool.poetry]
name = "graph_cast"
version = "1.0.0"
description = "ETL to cast tabular and json data types into graphs (collections of vertices and edges)"
authors = ["Alexander Belikov <alexander@growgraph.dev>"]

[tool.poetry.dependencies]
black = "^22.3.0"
neo4j = "^4.4.3"
networkx = "^2.6"
pandas = "^1.1.3"
python = "^3.9"
pyyaml = "^6"
pygraphviz = "^1.6"
python-arango = "^7.3.3"
xmltodict = "^0.12.0"
mypy = "^0.971"
isort = "^5.10.1"
autoflake = "^1.4"
pre-commit = "^2.20.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
