[tool.poetry]
name = "graph_cast"
version = "0.11.3"
description = "ETL to cast tabular and json data types into graphs (collections of vertices and edges)"
authors = ["Alexander Belikov <alexander@growgraph.dev>"]

[tool.poetry.dependencies]
neo4j = "^4.4.3"
networkx = "^2.6"
pandas = "^1.3.5"
python = "^3.9"
python-arango = "^7.5.3"
xmltodict = "^0.12.0"
dataclass-wizard = "^0.22.2"
suthing = {git = "ssh://git@github.com/growgraph/suthing.git", rev = "0.2.1"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
autoflake = "^1.4"
pre-commit-hooks = "^4.3.0"
pre-commit = "^2.20.0"
black = "^23.3.0"
isort = "5.11.5"
mypy = "^1.1.1"
language-formatters-pre-commit-hooks = "^2.4.0"
typing-extensions = "^4.5.0"


[tool.poetry.group.extra.dependencies]
pygraphviz = "^1.6"
