[tool.poetry]
name = "graph_cast"
version = "0.2.0"
description = "ETL to cast tabular and json data types into graphs (collections of vertices and edges)"
authors = ["Alexander Belikov <alexander@growgraph.dev>"]

[tool.poetry.dependencies]
black = "^22.3.0"
neo4j = "^4.4.3"
networkx = "^2.6"
pandas = "^1.1.3"
python = ">=3.9,<3.11"
pyyaml = "^5.3.1"
pygraphviz = "^1.6"
python-arango = "^7.3.3"
xmltodict = "^0.12.0"

[tool.poetry.group.dev.dependencies]
mypy = "^0.961"
vulture = "^2.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
