general:
    name: companies
resources:
-   resource_name: relations
    apply:
    -   target_vertex: company
        map:
            company_a: name
    -   target_vertex: company
        map:
            company_b: name
vertex_config:
    vertices:
    -   name: company
        fields:
        -   name
edge_config:
    edges:
    -   source: company
        target: company
        weights:
            direct:
            -   relation
            -   date
