general:
    name: debian-eco
    version: 0.0.1
resources:
-   resource_name: package
    apply:
    -   vertex: package
    -   key: dependencies
        apply:
        -   any_key: true
            apply:
            -   vertex: package
    -   source: maintainer
        target: package
    -   source: package
        target: package
        relation_from_key: true
    -   key: maintainer
        apply:
        -   vertex: maintainer
-   resource_name: bug
    apply:
    -   map:
            package: name
            bug_num: id
    -   vertex: package
    -   vertex: bug
vertex_config:
    vertices:
    -   name: package
        fields:
        -   name
        -   version
        identity:
        -   name
    -   name: maintainer
        fields:
        -   name
        -   email
        identity:
        -   email
    -   name: bug
        fields:
        -   id
        -   subject
        -   severity
        -   date
        identity:
        -   id
edge_config:
    edges:
    -   source: package
        target: package
    -   source: maintainer
        target: package
    -   source: package
        target: bug
