general:
    name: hr
resources:
-   resource_name: people
    apply:
    -   vertex: person
-   resource_name: departments
    apply:
    -   map:
            person: name
            person_id: id
    -   target_vertex: department
        map:
            department: name
vertex_config:
    vertices:
    -   name: person
        fields:
        -   id
        -   name
        -   age
        identity:
        -   id
    -   name: department
        fields:
        -   name
        identity:
        -   name
edge_config:
    edges:
    -   source: person
        target: department
