services:
    neo4j:
        image: ${IMAGE_VERSION}
        restart: "no"
        profiles: ["test.neo4j"]
        ports:
        -   "${NEO4J_PORT}:7474"
        -   "${NEO4J_BOLT_PORT}:7687"
        container_name: ${CONTAINER_NAME}
        volumes:
        -   ${STORE_FOLDER}/data:/data
        -   ${STORE_FOLDER}/plugins:/plugins
        -   ${STORE_FOLDER}/logs:/logs
        environment:
        -   NEO4J_AUTH=${NEO4J_AUTH}
        -   NEO4J_PLUGINS=${NEO4J_PLUGINS}
