name: Upload Python Package to PyPI

on:
    release:
        types: [published]

permissions:
    contents: read

jobs:
    pypi-publish:
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/graflo
        permissions:
            id-token: write

        steps:
        -   uses: actions/checkout@v4

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'
        -   name: Install uv
            uses: astral-sh/setup-uv@v5
            with:
                version: "0.8.14"
        -   name: Build and publish
            run: |
                uv build
                uv publish
            env:
                UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
